### ISSUE TITLE
Unfolding does not pass tests

### ISSUE THREAD

**Issue by jochym** [atztogo/phonopy#19]
The uninittests for unfolding fail on recent (1.10.7, 1.10.8) builds:

```
$ python test_unfolding.py 

 FF
 ======================================================================
 FAIL: test_Unfolding_NaCl (__main__.TestUnfolding)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "test_unfolding.py", line 39, in test_Unfolding_NaCl
     self._compare(weights, "unfolding.dat")
   File "test_unfolding.py", line 59, in _compare
     self.assertTrue((np.abs(weights_in_file - weights) < 1e-3).all())
 AssertionError: False is not true
 
 ======================================================================
 FAIL: test_Unfolding_SC (__main__.TestUnfolding)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "test_unfolding.py", line 54, in test_Unfolding_SC
     self._compare(weights, "unfolding_to_atoms.dat")
   File "test_unfolding.py", line 59, in _compare
     self.assertTrue((np.abs(weights_in_file - weights) < 1e-3).all())
 AssertionError: False is not true
 
 ----------------------------------------------------------------------
 Ran 2 tests in 30.289s
 
 FAILED (failures=2)
 
```

I have removed this test from the set to be able to build the package,
 but we need to fix it before 1.10.9.

**Comment by atztogo** [comment]
I fixed this issue. In some reason, the order of data changed, thought it is irrespective to physics. I found the data to be compared were too big (~2MB), so I use more processed and condensed data (~40kB) to be compared with for the test, and the data are ordered by the values.

**Comment by jochym** [comment]
Where is the fix? Is this just the problem with tests or actual code?

**Comment by atztogo** [comment]
You are quick! I merged it to develop branch.
