### ISSUE TITLE
pwscf with python3

### ISSUE THREAD

**Issue by baranas** [atztogo/phonopy#21]
Hi Togo,

it seems that `pwscf` parser is not working for `python3` version:

    Traceback (most recent call last):
      File "/usr/local/bin/phonopy", line 315, in <module>
        yaml_mode=settings.get_yaml_mode())
      File "/usr/local/lib/python3.5/dist-packages/phonopy/interface/__init__.py", line 73, in read_crystal_structure
        unitcell, pp_filenames = read_pwscf(unitcell_filename)
      File "/usr/local/lib/python3.5/dist-packages/phonopy/interface/pwscf.py", line 62, in read_pwscf
        pwscf_in = PwscfIn(open(filename).readlines())
      File "/usr/local/lib/python3.5/dist-packages/phonopy/interface/pwscf.py", line 191, in __init__
        self._collect(lines)
      File "/usr/local/lib/python3.5/dist-packages/phonopy/interface/pwscf.py", line 224, in _collect
        for tag, self._values in elements.iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'

You need to change `dict.iteritems` to `dict.items`.

Anyway thanks for such a nice package, I am using it for my PhD studies :).

**Comment by atztogo** [comment]
Thanks for your report. I hope I could fix it at c978c37e5daf2c96160d0074dc53f0ca2983ffa0. This fix will be available at the next release.

**Comment by shivamjani** [comment]
Hi Togo, 

Facing a similar issue in qe.py praser. Unable to use any functionality of QE with phonopy.

> python make_born_q2r.py scf.in Ca3Sb2.fc > BORN 

Traceback (most recent call last):
  File "/home/smj/Systems/Ca3Sb2/New/make_born_q2r.py", line 10, in <module>
    cell, _ = read_pwscf(primcell_filename)
  File "/home/smj/anaconda3/envs/**phonopy/lib/python3.9/site-packages/phonopy/interface/qe.py**", line 83, in read_pwscf
    pwscf_in = PwscfIn(f.readlines())
  File "/home/smj/anaconda3/envs/**phonopy/lib/python3.9/site-packages/phonopy/interface/qe.py**", line 211, in __init__
    self._collect(lines)
  File "/home/smj/anaconda3/envs/**phonopy/lib/python3.9/site-packages/phonopy/interface/qe.py**", line 254, in _collect
    getattr(self, self._set_methods[tag_name])()
  File "/home/smj/anaconda3/envs/**phonopy/lib/python3.9/site-packages/phonopy/interface/qe.py**", line 292, in _set_lattice
    raise RuntimeError(
RuntimeError: As a unit, alat, angstrom, and bohr can be only used.

**Comment by atztogo** [comment]
I can't see anything what is happening in detail. Please describe more detail.

**Comment by shivamjani** [comment]
Hi Togo,

Thanks a lot for your prompt response !!
I have raised this issue with more specific details with attached files and
links from which I followed the instructions of yours. Please help me to
resolve it!!

https://github.com/phonopy/phonopy/issues/153
https://github.com/phonopy/phonopy/tree/master/example/NaCl-QE-q2r


Regards

Shivam Jani
