### ISSUE TITLE
The SYMMETRY=.FALSE. gives error messages.

### ISSUE THREAD

**Issue by lyuwen** [atztogo/phonopy#58]
```
        _
  _ __ | |__   ___  _ __   ___   _ __  _   _
 | '_ \| '_ \ / _ \| '_ \ / _ \ | '_ \| | | |
 | |_) | | | | (_) | | | | (_) || |_) | |_| |
 | .__/|_| |_|\___/|_| |_|\___(_) .__/ \__, |
 |_|                            |_|    |___/
                                   1.12.0-r9

Python version 2.7.12
Spglib version 1.9.10
Creating displacements
Settings:
  Supercell: [2 2 1]
Spacegroup: P1 (1)

disp.yaml and supercells have been created.
Traceback (most recent call last):
  File "<HOME>/.local/bin/phonopy", line 559, in <module>
    filename="phonopy_disp.yaml")
  File "<HOME>/.local/bin/phonopy", line 121, in finalize_phonopy
    w.write(str(phpy_yaml))
  File "<HOME>/.local/lib/python2.7/site-packages/phonopy/interface/phonopy_yaml.py", line 258, in __str__
    return "\n".join(self.get_yaml_lines())
  File "<HOME>/.local/lib/python2.7/site-packages/phonopy/interface/phonopy_yaml.py", line 184, in get_yaml_lines
    self._symmetry.get_dataset()['international'])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by atztogo** [comment]
Thanks @lyuwen . I fixed. I hope it works at the latest version. I also added Si-nosym example.

**Comment by atztogo** [comment]
I will close this issue. Please re-open if it is not yet solved.
