### ISSUE TITLE
Some tests fail

### ISSUE THREAD

**Issue by yurivict** [atztogo/phonopy#80]
Tests fail in the FreeBSD port:
```
======================================================================
ERROR: Failure: ImportError (cannot import name _spglib)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/ports/science/py-phonopy/work-py27/phonopy-1.13.2.107/test/structure/test_grid_points.py", line 4, in <module>
    from phonopy.structure.grid_points import GridPoints
  File "/usr/ports/science/py-phonopy/work-py27/phonopy-1.13.2.107/phonopy/__init__.py", line 36, in <module>
    from phonopy.api_phonopy import Phonopy
  File "/usr/ports/science/py-phonopy/work-py27/phonopy-1.13.2.107/phonopy/api_phonopy.py", line 40, in <module>
    from phonopy.structure.symmetry import Symmetry
  File "/usr/ports/science/py-phonopy/work-py27/phonopy-1.13.2.107/phonopy/structure/symmetry.py", line 37, in <module>
    import phonopy.structure.spglib as spg
  File "/usr/ports/science/py-phonopy/work-py27/phonopy-1.13.2.107/phonopy/structure/spglib.py", line 35, in <module>
    from phonopy import _spglib as spg
ImportError: cannot import name _spglib
```

**Comment by atztogo** [comment]
How do you run this test?

**Comment by atztogo** [comment]
Is there any news?

**Comment by yurivict** [comment]
It installs ```_spglib.so```:
```
/usr/local/lib/python2.7/site-packages/phonopy/_spglib.so
```
but the tests fail.

They are run using ```python setup.py nosetests-2.7```. It fails with python-3.6 too.

The FreeBSD port exists, but tests fail in it. I don't know where do I go from here.

**Comment by atztogo** [comment]
Do you know if your PYTHONPATH is correctly set?

**Comment by yurivict** [comment]
I made it to run. It was actually running a command ```nosetests```. Changing to ```python setup.py test``` helped.

Now one case fails:
```
======================================================================
FAIL: test_IXS_G_to_L (spectrum.test_dynamic_structure_factor.TestDynamicStructureFactor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/py-phonopy/work-py27/phonopy-1.13.2.107/test/spectrum/test_dynamic_structure_factor.py", line 102, in test_IXS_G_to_L
    S[:, i].sum(axis=1), data_cmp[:, i].sum(axis=1), atol=1e-1)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 1443, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 780, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.1

(mismatch 10.0%)
 x: array([2.990558e+01, 8.017501e+00, 3.839426e+00, 2.339812e+00,
       1.633024e+00, 1.245578e+00, 7.558085e-05, 8.032014e-04,
       8.445302e-05, 1.604957e-01])
 y: array([2.990558e+01, 8.017501e+00, 3.839426e+00, 2.339812e+00,
       1.633024e+00, 1.245578e+00, 6.772900e-05, 3.625850e-04,
       2.829889e-02, 5.767737e-03])

----------------------------------------------------------------------
Ran 51 tests in 32.343s

FAILED (failures=1)
```

**Comment by atztogo** [comment]
Good!
Sorry, it's a known bug in the test script. See https://github.com/atztogo/phonopy/issues/79.
It was already fixed but it's not yet merged to master branch.

**Comment by yurivict** [comment]
Thank you for your help!
