### ISSUE TITLE
pdos error

### ISSUE THREAD

**Issue by HanmeiTang** [atztogo/phonopy#90]
Dear developers,

I have encountered some bug in plotting projected DOS. I used VASP to run phonon calculations. The calculations ended normally and all files are complete.  My structure is a supercell containing 128 atoms and the following is my `pdos.conf` file:

```
ATOM_NAME = Na P O
DIM = 1 1 1
MP = 8 8 8
SIGMA = 0.1
PDOS =  128
```
I can get the correct output if checkout to version `v1.14.2` but got different errors in `v2.1.1` and `v2.0.0`.

### Error message using Phonopy `v2.1.1`:

```
$ phonopy -p -s pdos.conf
        _
  _ __ | |__   ___  _ __   ___   _ __  _   _
 | '_ \| '_ \ / _ \| '_ \ / _ \ | '_ \| | | |
 | |_) | | | | (_) | | | | (_) || |_) | |_| |
 | .__/|_| |_|\___/|_| |_|\___(_) .__/ \__, |
 |_|                            |_|    |___/
                                       2.1.1

Python version 3.5.2
Spglib version 1.12.1
Crystal structure was read from "phonopy.yaml".
Mesh sampling mode
Settings:
  Sampling mesh: [8 8 8]
  Supercell: [1 1 1]
  Primitive matrix:
    [0.  0.  0.5]
    [0. 1. 0.]
    [-1.  0.  0.]
Spacegroup: P-42_1c (114)
Use -v option to watch primitive cell, unit cell, and supercell structures.

Forces and displacements are read from "FORCE_SETS".
Computing force constants...
Max drift of force constants: -0.068330 (yy) -0.000005 (xx)
Number of q-points on sampling mesh: 512
Calculating phonons on sampling mesh...
Calculating projected DOS...
Index number '128' is specified,
but it is not allowed to be larger than the number of atoms.
Traceback (most recent call last):
  File "/global/homes/h/hat003/.local/cori/3.5-anaconda/bin/phonopy", line 4, in <module>
    __import__('pkg_resources').run_script('phonopy==2.1.1', 'phonopy')
  File "/global/common/cori/software/python/3.5-anaconda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/global/common/cori/software/python/3.5-anaconda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/global/u2/h/hat003/.local/cori/3.5-anaconda/lib/python3.5/site-packages/phonopy-2.1.1-py3.5-linux-x86_64.egg/EGG-INFO/scripts/phonopy", line 1098, in <module>
    legend=([np.array(x) + 1 for x in pdos_indices]))
  File "/global/homes/h/hat003/.local/cori/3.5-anaconda/lib/python3.5/site-packages/phonopy-2.1.1-py3.5-linux-x86_64.egg/phonopy/api_phonopy.py", line 1750, in plot_projected_dos
    draw_grid=False)
  File "/global/homes/h/hat003/.local/cori/3.5-anaconda/lib/python3.5/site-packages/phonopy-2.1.1-py3.5-linux-x86_64.egg/phonopy/phonon/dos.py", line 487, in plot
    flip_xy=flip_xy)
  File "/global/homes/h/hat003/.local/cori/3.5-anaconda/lib/python3.5/site-packages/phonopy-2.1.1-py3.5-linux-x86_64.egg/phonopy/phonon/dos.py", line 134, in plot_partial_dos
    raise ValueError
ValueError
```

### Error message using Phonopy `v2.0.0`:

```
$  phonopy -p -s pdos.conf
        _
  _ __ | |__   ___  _ __   ___   _ __  _   _
 | '_ \| '_ \ / _ \| '_ \ / _ \ | '_ \| | | |
 | |_) | | | | (_) | | | | (_) || |_) | |_| |
 | .__/|_| |_|\___/|_| |_|\___(_) .__/ \__, |
 |_|                            |_|    |___/
                                       2.0.0

Python version 3.6.7
Spglib version 1.12.1
Crystal structure was read from "POSCAR".
Mesh sampling mode
Settings:
  Sampling mesh: [8 8 8]
  Supercell: [1 1 1]
Spacegroup: P-42_1c (114)
Use -v option to watch primitive cell, unit cell, and supercell structures.

Computing force constants...
Max drift of force constants: -0.068330 (zz) -0.000005 (xx)
Number of q-points on sampling mesh: 512
Calculating phonons on sampling mesh...
Traceback (most recent call last):
  File "/Users/hanmeiTang/miniconda3/bin/phonopy", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/hanmeiTang/repos/phonopy/scripts/phonopy", line 916, in <module>
    phonon.write_yaml_mesh()
  File "/Users/hanmeiTang/repos/phonopy/phonopy/api_phonopy.py", line 1234, in write_yaml_mesh
    self._mesh.write_yaml()
  File "/Users/hanmeiTang/repos/phonopy/phonopy/phonon/mesh.py", line 361, in write_yaml
    w.write("\n".join(lines))
OSError: [Errno 22] Invalid argument
```

### Normal output from `v1.14.2`

```phonopy -p -s pdos.conf
        _
  _ __ | |__   ___  _ __   ___   _ __  _   _
 | '_ \| '_ \ / _ \| '_ \ / _ \ | '_ \| | | |
 | |_) | | | | (_) | | | | (_) || |_) | |_| |
 | .__/|_| |_|\___/|_| |_|\___(_) .__/ \__, |
 |_|                            |_|    |___/
                                      1.14.2

Python version 3.6.7
Spglib version 1.11.1
Mesh sampling mode
Settings:
  Sampling mesh: [8 8 8]
  Supercell: [1 1 1]
Spacegroup: P-42_1c (114)
Computing force constants...
Max drift of force constants: -0.068330 (zz) -0.000005 (xx)
Number of q-points on sampling mesh: 512
Calculating phonons on sampling mesh...
Calculating partial PDOS...
/Users/hanmeiTang/miniconda3/lib/python3.6/site-packages/matplotlib/text.py:1191: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if s != self._text:
                 _
   ___ _ __   __| |
  / _ \ '_ \ / _` |
 |  __/ | | | (_| |
  \___|_| |_|\__,_|
```

**Comment by atztogo** [comment]
Can you send your input files to reproduce the problem?

**Comment by HanmeiTang** [comment]
Sure. The following files should reproduce the above error using v2.1.1.
[v2.1.1.zip](https://github.com/atztogo/phonopy/files/2955105/v2.1.1.zip)

**Comment by atztogo** [comment]
I could not reproduce your error. As is often the case, you might fail installation of phonopy. You have to remove older version completely before installing newer. Sometimes you need to remove files by hand. pip uninstall doesn't work well often. I used conda. I created conda new env (`conda create -n test`) and installed phonopy from conda-forge the latest phonopy and run your inputs. Then I got no error.

**Comment by HanmeiTang** [comment]
Thanks for the prompt reply! 

However, I actually got the same error even after creating a new environment. I am wondering if all the steps the same to yours?

```
$ conda create --name phonon_20190312
...
$ conda activate phonon_20190312
...
(phonon_20190312) $ conda install -c conda-forge phonopy
...
(phonon_20190312) $ phonopy -p -s pdos.conf
        _
  _ __ | |__   ___  _ __   ___   _ __  _   _
 | '_ \| '_ \ / _ \| '_ \ / _ \ | '_ \| | | |
 | |_) | | | | (_) | | | | (_) || |_) | |_| |
 | .__/|_| |_|\___/|_| |_|\___(_) .__/ \__, |
 |_|                            |_|    |___/
                                       2.1.1

Python version 3.7.1
Spglib version 1.12.1
Crystal structure was read from "phonopy.yaml".
Mesh sampling mode
Settings:
  Sampling mesh: [8 8 8]
  Supercell: [1 1 1]
  Primitive matrix:
    [0.  0.  0.5]
    [0. 1. 0.]
    [-1.  0.  0.]
Spacegroup: P-42_1c (114)
Use -v option to watch primitive cell, unit cell, and supercell structures.

Forces and displacements are read from "FORCE_SETS".
Computing force constants...
Max drift of force constants: -0.068330 (zz) -0.000005 (xx)
Number of q-points on sampling mesh: 512
Calculating phonons on sampling mesh...
Calculating projected DOS...
Index number '128' is specified,
but it is not allowed to be larger than the number of atoms.
Traceback (most recent call last):
  File "/Users/hanmeiTang/miniconda3/envs/phonon_20190312/bin/phonopy", line 1098, in <module>
    legend=([np.array(x) + 1 for x in pdos_indices]))
  File "/Users/hanmeiTang/miniconda3/envs/phonon_20190312/lib/python3.7/site-packages/phonopy/api_phonopy.py", line 1750, in plot_projected_dos
    draw_grid=False)
  File "/Users/hanmeiTang/miniconda3/envs/phonon_20190312/lib/python3.7/site-packages/phonopy/phonon/dos.py", line 487, in plot
    flip_xy=flip_xy)
  File "/Users/hanmeiTang/miniconda3/envs/phonon_20190312/lib/python3.7/site-packages/phonopy/phonon/dos.py", line 134, in plot_partial_dos
    raise ValueError
ValueError
```

**Comment by atztogo** [comment]
Your unit cell is not a primitive cell. The primitive cell is automatically found and has 64 atoms. So the index 128 doesn't exist. If you avoid to set automatically the primitive cell, you have to specify it manually, i.e.,

```
phonopy pdos.conf --pa 1 0 0 0 1 0 0 0 1 -s -p
```

**Comment by HanmeiTang** [comment]
This works. Thanks so much!

**Comment by 0410wang** [comment]
the error will be solved if you change the value with the TAG 'PDOS' according the number of atoms in your primitive cell.
